version: "3"

services:
  database:
    build:
      context: "./bin/${DATABASE}"
    container_name: '${COMPOSE_PROJECT_NAME}-${COMPOSE_PROJECT_VERSION}-${DATABASE}'
    restart: 'always'
    ports:
      - "${HOST_MACHINE_MYSQL_PORT}:3306"
    volumes: 
      - ${MYSQL_DATA_DIR-./data/mysql}:/var/lib/mysql
      - ${MYSQL_LOG_DIR-./logs/mysql}:/var/log/mysql
      - ${MYSQL_SCRIPTS_DIR-./config/mysql/scripts}:/docker-entrypoint-initdb.d/
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - network
  
  
networks:
  network:
    # driver_opts:
    #   com.docker.network.bridge.host_binding_ipv4: "172.20.0.1"
    # ipam:
    #   config:
    #     - subnet: "172.20.0.0/16"
